### ISSUE TITLE
Cycles that can reach equilibrium

### ISSUE THREAD

**Issue by liron00** [ds300/derivablejs#22]
const selectedChild = derivation(() => {
      return prop.children.get()[selectedIndex.get()] || null
    }).react(selectedChild => {
      if (!selectedChild) {
        selectedIndex.set(prop.children.get().length - 1)
      }
    }

Here, `prop.children` is an atom containing an array of children objects passed down from a parent component. The parent component may mutate `prop.children` any time. If `prop.children` has length 3 and `selectedIndex` is 2, and then `prop.children` loses an element, it makes sense to react to that change of state by adjusting the selectedIndex to 1 so a valid child is still selected.

Currently Derivable throws an error complaining about a cycle. But this cycle is guaranteed to reach equilibrium after 1 iteration because of the "if" statement.

I propose that in general, the pattern of writing "cycles of react & set that reach equilibrium in provably-constant number of iterations" is a good programming pattern, and shouldn't throw an error.

**Comment by ds300** [comment]
Cycles are not happening I'm afraid. I've been down this road before and
what it boils down to is that state is acyclic by its very nature. Trying
to get around that fact only causes problems. Sucks, I know, but that's
life.

Here we must do as the Germans do and examine our shit in cold light.

So it turns out that an atom has a dependency? Then we simply must turn the
atom into a derivation and capture its dependency.

```javascript
const desiredIndex = atom(3);
const maxIndex = prop.children.derive(xs => xs.length - 1);
const selectedIndex = desiredIndex.derive(Math.min, maxIndex);
```

But selectedIndex must be an atom you say? Lenses to the rescue!

```javascript
const selectedIndex = atom(3).lens({
  get: i => Math.min(i, maxIndex.get()),
  set: (_, j) => j
});
```

Now you get the best of both worlds.

Hope that helps.

const selectedChild = derivation(() => {
  return prop.children.get()[selectedIndex.get()] || null
}).react(selectedChild => {
  if (!selectedChild) {
    selectedIndex.set(prop.children.get().length - 1)
  }
}

Here, prop.children() is an atom containing an array of children objects
passed down from a parent component. The parent component may mutate
prop.children() any time. If prop.children() has length 3 and selectedIndex
is 2, and then prop.children() loses an element, it makes sense to react to
that change of state by adjusting the selectedIndex to 1 so a valid child
is still selected.

Currently Derivable throws an error complaining about a cycle. But this
cycle is guaranteed to reach equilibrium after 1 iteration because of the
"if" statement.

I propose that in general, the pattern of writing "cycles of react & set
that reach equilibrium in provably-constant number of iterations" is a good
programming pattern, and shouldn't throw an error.

—
Reply to this email directly or view it on GitHub
<https://github.com/ds300/derivablejs/issues/22>.

**Comment by liron00** [comment]
I get your solution (or perhaps workaround) but I think I'm still onto something here. Some points:

1. There are two kinds of cycles because the graph has two kinds of arrows: A "derivation arrow (`=>`)" and a "set arrow" (`->`). I think we should only prevent cycles of derivation arrows, i.e. allow `selectedIndex => selectedChild -> selectedIndex`.

2. Consider the case where at the time of someone's index being invalid, I want to instead choose the `selectedIndex` to be the number of seconds past the hour (mod maxIndex). I do think these are important semantics to have, and your workaround would become quite contrived. Admittedly it's a pretty contrived example, but it's important to remember that setters run at precise moments in time, they aren't "timeless" like derivations.

3. Right now, instead of using your workaround, I can use a different workaround: I can simply wrap the selectedIndex.set() call in a setTimeout(), and everything works and the code is totally readable.

**Comment by ds300** [comment]
I feel your pain. Really, I do. Alas, like I said, I've [been down this road before](https://github.com/ds300/derivablejs/issues/8) and cannot find a way to allow cycles which doesn't trample all over the other good stuff that Derivables give us. If you can figure out how to do that I'd be absolutely thrilled to include the solution in DerivableJS, but I would also very surprised indeed because all my thinking on the subject pointed toward the fact that state just isn't cyclic.

> Right now, instead of using your workaround, I can use a different workaround: I can simply wrap the selectedIndex.set() call in a setTimeout(), and everything works and the code is totally readable.

Yep, but you lose out on consistency and laziness. e.g. if some other reactor comes along depending on `selectedndex`, it also needs to know that `selectedIndex` might get too big, and how to fix that by creating a cycle. I'm not willing to endorse that kind of mess. I think if you want that kind of thing, then it makes sense to have to explicitly jump through hoops like setTimeout.

**Comment by liron00** [comment]
After reading this and the other thread, I concede on all points. I'm glad you've thought this through so well.
