### ISSUE TITLE
Have .derive('fieldName') call .get() when appropriate

### ISSUE THREAD

**Issue by liron00** [ds300/derivablejs#34]
This is minor but I often use Facebook's immutable.js library and store an immutable.Map inside an atom. I can't use `atom(Map({a: 5})).derive('a')` because what I need to do is `.derive(m => m.get('a'))`.

**Comment by ds300** [comment]
Oh man I'd love to be able to do this but have no idea how. I'm also a big user of Immutable, but I can't make it a dependency of DerivableJS and I can't special-case things with a `.get` method because that would just be crazy.

At some point I read about a proposal to introduce a ['well-known symbol'](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Well-known_symbols) for property lookup, the main argument being to allow lexical destructuring of es6 `Map`s, but I don't think it ever became a thing. Shame.

**Comment by liron00** [comment]
Maybe derivable can look for a .derivableGet method on the object, and then
users like me can instantiate a custom subclass of immutable.Map to
implement .derivableGet as .get.


On Thursday, December 24, 2015, David Sheldrick <notifications@github.com>
wrote:

> Oh man I'd love to be able to do this but have no idea how. I'm also a big
> user of Immutable, but I can't make it a dependency of DerivableJS and I
> can't special-case things with a .get method because that would just be
> crazy.
>
> At some point I read about a proposal to introduce a 'well-known symbol'
> <https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Well-known_symbols>
> for property lookup, the main argument being to allow lexical destructuring
> of es6 Maps, but I don't think it ever became a thing. Shame.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ds300/derivablejs/issues/34#issuecomment-167168849>.
>


-- 
--
*Liron Shapira*, Chief Science Officer
US: +1 408.621.6667 | 303 Bryant St, Mountain View, CA 94041
Israel: +972 54.457.5776 | Azrieli Round Tower Fl 29, 132 Menachem Begin
Rd, Tel Aviv, Israel 67021
<http://i.imgur.com/dpMvVRI.png>

**Comment by oskbor** [comment]
Yeah something to ease the use of immutable.js would be nice!

**Comment by ds300** [comment]
I must admit that the .derivableGet idea doesn't appeal to me because not only do you have to subclass Map, but you have to override all the methods which return Maps and you have to convert maps that come from elsewhere and it's just a mess.

I think a plain old function wins here. e.g.

```javascript
function iget(arg) {
  if (typeof arg === 'string') {
    return m => m.get(arg);
  } else {
    // assume arg instanceof Array
    return arg.map(k => m => m.get(k));
  }
}

const a = thing.derive(iget('a'));
const [b, c, d] = thing.derive(iget(['b', 'c', 'd']));
```

Is it really that big a deal to call one extra function? Plus you can mix this with standard property lookup.

```javascript
const [val, count] = map.derive([iget('key'), 'size']);
```

**Comment by liron00** [comment]
I'll throw out another idea:

Have `x.derive('foo')` check if `x.get().get` is a function, and if so, call `x.get().get('foo')`. Otherwise return `x.get().foo`.

The only downside is when `x.get().get` is a function but the programmer wanted `x.get().foo` anyway. In that rare case, the programmer can just say `x.derive(x => x.foo)`.

**Comment by ds300** [comment]
I [already dismissed](https://github.com/ds300/derivablejs/issues/34#issuecomment-167168849) that idea.

- It's magical behaviour that I wouldn't want to have to explain to beginners, or anybody really.
- It could cause bugs for people who aren't aware of it.
- It could cause bugs for people who aren't aware of .get methods on the types they are using.
- If we do it the way you say, i.e. *'check if x.get().get is a function [...]'* then we have to dereference x at initialization time, which is a non-starter. The only alternative I can think of is checking for .get every time a derivation is evaluated. This wouldn't incur huge overhead, but it's still very undesirable.

I tend to prioritise simplicity over concision, and I think the extra concision is definitely not worth the extra complexity in this case.

**Comment by liron00** [comment]
Ok makes sense
