### ISSUE TITLE
Todo MVC

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [ds300/derivablejs#46]
Rewrote the Todo MVC example.  Published it as an [example](https://github.com/SwedishConneciton/todomvc-derivable).  Thanks for the cool library!  Like the whole idea on composing state.  Going to plug it with a blog soon.

**Comment by ds300** [comment]
This is super cool, thanks! :D

You might be interested in the fact that recently @andreypopp made an extremely nice React integration layer for DerivableJS over at [andreypopp/react-derivable](https://github.com/andreypopp/react-derivable). Which certainly beats the toy thing from my original TodoMVC example.

I'm going to close this since it's not an issue. :+1:

**Comment by MatthewDavidCampbell** [comment]
That guy is everywhere.  Hadn't seen his wrapper.  Thanks.  Will reference it.
