### ISSUE TITLE
Add lazyness to derive calculations

### ISSUE THREAD

**Issue by zerkalica** [ds300/derivablejs#55]
It's not a bug, but not accuracy. Derive callback called on derive.react without updating source value.

```js
        const until = atom(false)
        const derive = until.derive((v) => {
            console.log('called!')
            return v
        })
        derive.react(() => {}, {skipFirst: true}) // shows called!
```

**Comment by ds300** [comment]
This is acceptable behaviour. Derivation functions must not have side effects for this reason; i.e. DerivableJS does not make strong guarantees about **when** derivations are calculated, only about when reactors are executed.

This is one case where total laziness is impossible to achieve, since you need to know the value of something to decide whether or not it has changed.

**Comment by zerkalica** [comment]
Ok, thanks.
